### PR TITLE
Dynamic backends

### PR DESCRIPTION
**Pull request by floored1585**
This PR allows generation of a dynamic list of backend servers, pulled from an ansible group.

Usage:

```
haproxy_backend:
  - name: example_backend
    mode: http
    balance: roundrobin
    server_dynamic:
      - group: 'my_backend_hosts'
        listen_port: '80'
        param:
          - check
```

### CODE REVIEW

**Comment by floored1585** [comment]
Hi, any thoughts on this, or anything that needs to be tweaked?

**Comment by floored1585** [comment]
Just a feature add, hoping to get approval or feedback, thanks!

**Comment by floored1585** [comment]
bump, any chance to get this merged?

**Comment by tersmitten** [comment]
@floored1585 Yes

**Pull request merged**
