### PR TITLE
cleaning up template whitespace

### PR DESCRIPTION
**Pull request by floored1585**
Hello,

This PR cleans up white space in the haproxy.cfg templates.  There were many extra newlines, which made the resulting file difficult to parse visually.  This commit leaves newlines only where they are required or are visually pleasing.  Please let me know if anything needs to be tweaked for this to be accepted.

### CODE REVIEW

**Comment by floored1585** [comment]
I added a second commit here to move the backend `acl` entry above where it can be used (the `stick` section can use an ACL)

**Comment by tersmitten** [comment]
> I added a second commit here to move the backend acl entry above where it can be used (the stick section can use an ACL)

Can you move this bug fix to a separate PR?

**Comment by everywan-dev** [comment]
ETA to merge this into master?

**Comment by tersmitten** [comment]
I prefer the bugfix separate from the whitespace change. It also has conflicts that must be resolved.

**Comment by everywan-dev** [comment]
Yes, but have important "PR" (like #60) that need to be in master because a bad application can have a disrupt in a service. Now, I think that the most important is merge this pr #80 and pr #60 into master.

**Comment by tersmitten** [comment]
#60 is already in master

**Comment by everywan-dev** [comment]
How can indicate that I can want a reload instead of restart?

**Comment by floored1585** [comment]
Okay, moved the bug fix to a different PR and fixed the merge conflicts here

**Comment by floored1585** [comment]
Let me know if anything else needs to change here.

**Comment by floored1585** [comment]
If this is not merged soon there will be more merge conflicts to resolve.  If anything is lacking please let me know.

**Comment by tersmitten** [comment]
You're right, but I'm not that confident in merging it. It needs major testing on my side. Sorry.

**Comment by floored1585** [comment]
OK if there is anything I can do to help let me know.  It's just removing redundant whitespace; all text output in the templates have newlines at the end already as far as I can tell.

**Comment by floored1585** [comment]
The dangerous lines are these: https://github.com/Oefenweb/ansible-haproxy/blob/bd1dcb7070f36c60d7888fbb6726499757dee64e/templates/etc/haproxy/backend.cfg.j2#L53
(ones with output then a `{% ... %}` at the end -- there will be no newline because of the `%`.

**Comment by floored1585** [comment]
Just wanted to bump this again; the change looks scary but due to the way the templating works the only lines that should be concerning are the ones formatted as mentioned above, and I left the extra whitespace after those.

**Comment by floored1585** [comment]
Could you take a look please? I'd like to be able to use this upstream repo but have had to fork away for now...

**Comment by tersmitten** [comment]
I understand, but what value does it add (except for a lot of conflicts in other PR's)?

**Comment by floored1585** [comment]
It generates config that is readable and easily viewed by people. When
there are hundreds of random newlines the config is very difficult to read.
If you don't want the change in this PR let me know and I will close it,
instead of waiting on for a long time. That is your choice but don't give
me false hope :)

**Comment by floored1585** [comment]
I'd be willing to resolve the existing conflicts to master if there is commitment to merge these changes, otherwise I'll go ahead and close this out.

**Comment by tersmitten** [comment]
> there is commitment to merge these changes

There's commitment. I'll merge them as soon as possible.

**Comment by floored1585** [comment]
Great! I have rebased the change on current master, this is now good to merge.

For reference, any time we have `{{ ... }}` followed by `{% ... %}` on the same line, we have to add an extra newline, because the natural newline gets removed by the `{% ... %}`. Just something to keep in mind. I fixed a few of those cases that were missing newlines here also, which probably fixed a few really rare "these two config lines ended up mashed together on the same line" bugs.

**Pull request merged**
