### PR TITLE
Move log-format to correct section

### PR DESCRIPTION
**Pull request by adrianmoisey**
Fixes https://github.com/Oefenweb/ansible-haproxy/issues/51

### CODE REVIEW

**Comment by tersmitten** [comment]
Can you have a look at the failing tests?

**Comment by adrianmoisey** [comment]
I've tested locally, and I can't get the tests to fail. Can you rerun the tests?

**Comment by adrianmoisey** [comment]
> I've tested locally, and I can't get the tests to fail. Can you rerun the tests?

Oh, I was testing the wrong branch. My bad! Will sort it out soon.

**Comment by adrianmoisey** [comment]
For some reason I can't reproduce this locally :/

**Comment by tersmitten** [comment]
I'll have a look at it

**Comment by tersmitten** [comment]
@adrianmoisey It was a white-space issue

**Pull request closed without merging**
