### PR TITLE
Added redispatch 

### PR DESCRIPTION
**Pull request by timrvv**
Added support for option redispatch in defaults, listen, backend sections.

### CODE REVIEW

**Comment by tersmitten** [comment]
https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#option redispatch

**Comment by tersmitten** [comment]
I think this can be implemented using the `option` and `no option` settings of this role:

```
{% for option in listen.option | default([]) %}
  option {{ option }}
{% endfor %}

{% for option in listen.no_option | default([])  %}
  no option {{ option }}
{% endfor %}
```

Do you agree?

**Comment by timrvv** [comment]
Yeah, didn't think about of using "option" array for this. Its simpler.
Though currently there is not support for of no_option in backends and defaults. I'll add them in different PR.

**Comment by tersmitten** [comment]
> Though currently there is not support for of no_option in backends and defaults. I'll add them in different PR.

That would be super useful :-), thanks in advance

**Comment by timrvv** [comment]
Here is it :)
https://github.com/Oefenweb/ansible-haproxy/pull/70

**Pull request closed without merging**
