### PR TITLE
Add option to define http request and redirects for listen frontend

### PR DESCRIPTION
**Pull request by tersmitten**
Fixes #12, fixes #16

### CODE REVIEW

**Comment by tersmitten** [comment]
@haad, @wyaeld @boskiv Can one of you guys test the new functionality (and check if it suits your needs)?

**Comment by haad** [comment]
yes but I have to add flush handlers back :/

**Comment by tersmitten** [comment]
Yes. I removed that because it breaks backwards compatibility and I don't think everybody wants that behavior. There's probably a workaround for your particular use case.

**Comment by haad** [comment]
I think this could be merge, I have tested generated config and it works.

**Comment by tersmitten** [comment]
Ok. Thanks for testing. I'll merge it tomorrow.

**Pull request merged**
