### PR TITLE
Add option to define http-request and redirects for listen/frontend

### PR DESCRIPTION
**Pull request by haad**

### CODE REVIEW

**Comment by tersmitten** [comment]
Can you add documentation and an example how to use this?

**Comment by tersmitten** [comment]
Why do we need the flush handlers?

**Comment by haad** [comment]
For me it makes sense to flush handlers after haproxy deployment as other services might depend on working haproxy so right after we deploy haproxy we want to make sure new config is applied.

**Comment by haad** [comment]
I will add some documentation to describe usage of new options

**Comment by tersmitten** [comment]
See #17 I'm almost done

**Comment by tersmitten** [comment]
Fixed in #17

**Pull request closed without merging**
