### PR TITLE
Add support for multiple backends

### LINKED ISSUE #35: problem with multiple backends
Hello,

Maybe just a problem on my side but here's the case.

I put in my host var

~~~
    acl:
      - string: is_exa1 hdr(host) -i example1.com
      - string: is_exa2 hdr_end(host) -i example2.com
    use_backend:
      - exa-1 if is_exa1
      - exa-2 if is_exa1
    default_backend: example-www
~~~

and then i get 

~~~
use_backend [u'exa-1 if is_exa1', u'exa-2 if exa2']
~~~

in `haproxy.cfg`. ACL is working.

Bug or something wrong on my side ?

### PR DESCRIPTION
**Pull request by tersmitten**
Fixes #35

### CODE REVIEW

**Comment by tersmitten** [comment]
@ojan I testing it now, can you verify that it works for your use-case?

**Comment by tersmitten** [comment]
This seems to work:

```
# test file for haproxy
---
- hosts: all
  remote_user: vagrant
  sudo: true
  roles:
    - ../../
  vars:
    haproxy_frontend:
      - name: http
        bind:
          - listen: "{{ ansible_eth0['ipv4']['address'] }}:80"
        mode: http
        acl:
          - string: is_exa1 hdr(host) -i example1.com
          - string: is_exa2 hdr_end(host) -i example2.com
        use_backend:
          - exa-1 if is_exa1
          - exa-2 if is_exa1
        default_backend: example-www
    haproxy_backend:
      - name: example-www
        mode: http
        balance: roundrobin
        server: []
      - name: exa-1
        mode: http
        balance: roundrobin
        server: []
      - name: exa-2
        mode: http
        balance: roundrobin
        server: []
```

**Comment by tersmitten** [comment]
This also works:

```
# test file for haproxy
---
- hosts: all
  remote_user: vagrant
  sudo: true
  roles:
    - ../../
  vars:
    haproxy_frontend:
      - name: http
        bind:
          - listen: "{{ ansible_eth0['ipv4']['address'] }}:80"
        mode: http
        use_backend: '%[req.hdr(host),lower,map_dom(/etc/haproxy/haproxy_backend.map,example-www)]'
        default_backend: example-www
    haproxy_backend:
      - name: example-www
        mode: http
        balance: roundrobin
        server: []
```

```
vagrant@ansible-haproxy-ubuntu-1404:/etc/haproxy$ cat haproxy_backend.map 
#domainname  backendname
app1.domain1.com bk_app1
app1.domain2.com bk_app1
app2.domain1.com bk_app2
app2.domain2.com bk_app2
```

**Comment by ojan** [comment]
works like a charm for me. Thanks a lot :-)

**Comment by tersmitten** [comment]
Great! Was on my TODO list for a while :-)

**Pull request merged**
