### PR TITLE
add ability to trigger ssl_redirect as a 301

### PR DESCRIPTION
**Pull request by wyaeld**
frontend change to allow forcing a redirect from http over to https for security

### CODE REVIEW

**Comment by tersmitten** [comment]
Can you add documentation? After that I'll merge it

**Comment by boskiv** [comment]
How I can implement it without this PR ?

**Comment by tersmitten** [comment]
@boskiv What do you mean?

**Comment by boskiv** [comment]
@tersmitten How I can do redirect from http to https with your playbook ?

**Comment by tersmitten** [comment]
@boskiv You can't. At the moment I always do that at application level.

**Comment by tersmitten** [comment]
Fixed in #17

**Pull request closed without merging**
